### ISSUE TITLE
PHP-DI update

### ISSUE THREAD

**Issue by mnapoli** [TomBZombie/php-dependency-injection-benchmarks#16]
Hi! Thanks for updating the repo, I ran the benchmarks and profiled the code, and found some easy optimizations in PHP-DI. I've released 5.0.3 which improves performances, especially for the test 3 which was very bad.

It's just to let you know. Thanks :)

**Comment by mnapoli** [comment]
Closing since there isn't much to do I guess

**Comment by TomBZombie** [comment]
Cheers! I've updated it to now use composer to pull in the latest version. I'll re-run the benchmarks so that the sample results.html files are up to date.

If you have any tweaks for the initialisation code, feel free to create a PR.
